DatabaseInitializers/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using EmployeeDeskBook.Models;
using EmployeeDeskBook.Notification;
using Contract;
using Domain;


namespace EmployeeDeskBook.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        IUnitOfWork _uow;

        public AdminController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public ActionResult Index()
        {
            var users = _uow.UserReposityory.GetWithInclude(u => u.Role).ToList();
            return View(users);
        }

        public ActionResult Create()
        {
            int adminId = 1;

            List<Roles> otherRoles = _uow.RoleRepository.GetItemsList().Where(e => e.Id != adminId).ToList();
            SelectList roles = new SelectList(otherRoles, "Id", "Name");
            ViewBag.Roles = roles;
            return View();
        }


        [HttpPost]
        public ActionResult Create(User user)
        {
            int adminId = 1;

            List<Roles> otherRoles = _uow.RoleRepository.GetItemsList().Where(e => e.Id != adminId).ToList();
            SelectList roles = new SelectList(otherRoles, "Id", "Name");
            ViewBag.Roles = roles;
            Notification.Notification notifi = null;

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.UserReposityory.Create(user);
                    _uow.Save();
                }
                catch
                {
                    notifi = new Notification.Notification(NotificationType.Error, "Ошибка сохранения данных о пользователе");
                    NotificationList.Add(notifi);
                    return View(user);
                }
                notifi = new Notification.Notification(NotificationType.Notice, "Пользователь создан успешно");
                NotificationList.Add(notifi);
                return RedirectToAction("Index");
            }
            
            notifi = new Notification.Notification(NotificationType.Error, "Ошибка, заполните все поля правильно");
            NotificationList.Add(notifi);
            return View(user);
        }


        public ActionResult Edit(int id)
        {
            int adminId = 1;

            User user = _uow.UserReposityory.GetWithInclude(e => e.Role).FirstOrDefault(e => e.Id == id);
            if (user.RoleId == 1)
            {
                List<Roles> role = new List<Roles>();
                role.Add(user.Role);
                SelectList roles = new SelectList(role, "Id", "Name");
                ViewBag.Roles = roles;
            }
            else
            {
                List<Roles> otherRoles = _uow.RoleRepository.GetItemsList().Where(e => e.Id != adminId).ToList();
                SelectList roles = new SelectList(otherRoles, "Id", "Name");
                ViewBag.Roles = roles;
            }
            return View(user);
        }


        [HttpPost]
        public ActionResult Edit(User user)
        {
            int adminId = 1;

            if (user.RoleId == adminId)
            {
                List<Roles> role = new List<Roles>();
                role.Add(user.Role);
                SelectList roles = new SelectList(role, "Id", "Name");
                ViewBag.Roles = roles;
            }
            else
            {
                List<Roles> otherRoles = _uow.RoleRepository.GetItemsList().Where(e => e.Id != adminId).ToList();
                SelectList roles = new SelectList(otherRoles, "Id", "Name");
                ViewBag.Roles = roles;
            }

            Notification.Notification notifi = null;
            
            if (ModelState.IsValid)
            {
                try
                {
                    _uow.UserReposityory.Update(user);
                    _uow.Save();
                }
                catch
                {
                    notifi = new Notification.Notification(NotificationType.Error, "Ошибка сохранения данных о пользователе");
                    NotificationList.Add(notifi);
                    return View(user);
                }

                notifi = new Notification.Notification(NotificationType.Notice, "Иформация о пользователе успешно сохранена");
                NotificationList.Add(notifi);
                return RedirectToAction("Index");
            }

            notifi = new Notification.Notification(NotificationType.Error, "Ошибка, заполните все поля правильно");
            NotificationList.Add(notifi);
            return View(user);
        }


        public ActionResult Delete(int id = 0)
        {
            User user = _uow.UserReposityory.GetWithInclude(e => e.Role).FirstOrDefault(e => e.Id == id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Notification.Notification notifi = null;
            User user =_uow.UserReposityory.GetWithInclude(e => e.Role).FirstOrDefault(e => e.Id == id);
            try
            {
                _uow.UserReposityory.Delete(user.Id);
                _uow.Save();
            }
            catch
            {
                notifi = new Notification.Notification(NotificationType.Error, "Ошибка удаления пользователя");
                NotificationList.Add(notifi);
                return View(user);
            }
            notifi = new Notification.Notification(NotificationType.Notice, "Пользователь успешно удален");
            NotificationList.Add(notifi);
            return RedirectToAction("Index");
        }

    }
}

DatabaseInitializers/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using EmployeeDeskBook.Models;
using System.IO;
using System.Text.RegularExpressions;
using EmployeeDeskBook.Notification;
using Domain;
using Contract;
using AutoMapper;

namespace EmployeeDeskBook.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {

        IUnitOfWork _uow;
      
        public EmployeesController(IUnitOfWork uow )
        {
            _uow = uow;

        }

        public ActionResult Index(EmployeeFilteringViewModel model, int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);


            IEnumerable<Employee> employees = _uow.EmployeeRepository.GetWithInclude(o => o.Organization,e => e.Departament);
            Notification.Notification notifi = null;

            IList<Departament> departaments = _uow.DepartamentRepository.GetItemsList().ToList();
            departaments.Insert(0, new Departament { Id = 0, Name = "Все" });
            ViewBag.Departaments = new SelectList(departaments, "Id", "Name");

            if (model.DepartamentId != null && model.DepartamentId != 0)
            {
                int depId = Convert.ToInt32(model.DepartamentId);
                employees = _uow.EmployeeRepository.GetWithInclude(e => e.Organization, e => e.Departament);
                employees = employees.Where(e => e.DepartamentId == depId).OrderBy(e => e.Id);
            }

            if (!String.IsNullOrEmpty(model.FromSortDate) && !String.IsNullOrEmpty(model.ToSortDate))
            {
                DateTime fromDate;
                DateTime toDate;
                bool corretDate = true;
                if (DateTime.TryParse(model.FromSortDate, out fromDate) == false)
                {
                    notifi = new Notification.Notification(NotificationType.Error, "Ошибка!Введите корректные данные дат для фильтрации");
                    NotificationList.Add(notifi);
                    ModelState.AddModelError("FromSortDate", "");
                    corretDate = false;
                }
                if (DateTime.TryParse(model.ToSortDate, out toDate) == false)
                {
                    notifi = new Notification.Notification(NotificationType.Error, "Ошибка!Введите корректные данные дат для фильтрации");
                    NotificationList.Add(notifi);
                    ModelState.AddModelError("ToSortDate", "");
                    corretDate = false;
                }


                if (corretDate)
                {
                    employees = employees.Where(e => e.BirthDate >= fromDate && e.BirthDate <= toDate);
                }
            }
            else if (!String.IsNullOrEmpty(model.FromSortDate))
            {
                DateTime fromDate;
                if (DateTime.TryParse(model.FromSortDate, out fromDate))
                {
                    employees = employees.Where(e => e.BirthDate >= fromDate);
                }
                else
                {
                    notifi = new Notification.Notification(NotificationType.Error, "Ошибка!Введите корректные данные дат для фильтрации");
                    NotificationList.Add(notifi);
                    ModelState.AddModelError("FromSortDate", "");
                }
            }
            else if (!String.IsNullOrEmpty(model.ToSortDate))
            {
                DateTime toDate;
                if (DateTime.TryParse(model.ToSortDate, out toDate))
                {
                    employees = employees.Where(e => e.BirthDate <= toDate);
                }
                else
                {
                    notifi = new Notification.Notification(NotificationType.Error, "Ошибка!Введите корректные данные дат для фильтрации");
                    NotificationList.Add(notifi);
                    ModelState.AddModelError("ToSortDate", "");
                }
            }


            IEnumerable<Employee> employeesPager = employees.OrderBy(e => e.Id).Skip<Employee>((pageNumber - 1) * pageSize).Take<Employee>(pageSize);
            Pager pager = new Pager { PageNumber = pageNumber, PageSize = pageSize, TotalItems = employees.Count<Employee>() };

            model = Mapper.Map<IEnumerable<Employee>, EmployeeFilteringViewModel>(employeesPager, model);
            model = Mapper.Map<Pager, EmployeeFilteringViewModel>(pager, model);

            return View(model);

        }

        [HttpPost]
        public ActionResult DepartamentsList(int orgId)
        {
            Organization organization = _uow.OrganizationRepository.GetItemsList().FirstOrDefault(e => e.Id == orgId);
            List<Departament> departaments = organization.Departaments.ToList<Departament>();
            return PartialView(departaments);
        }
        public ActionResult AutocompleteSearch(string term)
        {
            string text = null;
            Regex regex = new Regex(@"[А-ЯЁа-яё]+");

            List<string> fullNames = new List<string>();
            List<Employee> employees = null;
            MatchCollection mc = regex.Matches(term);

            if (mc.Count == 1)
            {
                string name = mc[0].Value;
                employees = _uow.EmployeeRepository.GetItemsList().Where(e => e.Name.Contains(name) || e.Surname.Contains(name)).ToList();
            }
            else if (mc.Count == 2)
            {
                string name = mc[0].Value;
                string surname = mc[1].Value;

                employees = _uow.EmployeeRepository.GetItemsList().Where(e => e.Name.Contains(name) || e.Surname.Contains(surname)).ToList();

            }

            if (mc.Count != 0 && mc.Count <= 2)
            {
                foreach (Employee employee in employees)
                {
                    text += employee.Name;
                    text += " " + employee.Surname;

                    fullNames.Add(text);
                    text = null;
                }

            }

            return Json(fullNames.Distinct<string>(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult EmployeeSearch(string name, string surname)
        {
            IEnumerable<Employee> employees = null;
            if (name.Equals(surname))
            {
               
                employees = _uow.EmployeeRepository.GetWithInclude(e => e.Organization.Departaments).Where(c => c.Name.Contains(name) || c.Surname.Contains(surname));
            }
            else
            {
                employees = _uow.EmployeeRepository.GetWithInclude(e => e.Organization.Departaments).Where(a => a.Name.Contains(name) && a.Surname.Contains(surname));
            }
            return PartialView(employees);
        }
        public ActionResult Details(int id)
        {

            Employee employee = _uow.EmployeeRepository.GetWithInclude(e => e.Picture, o => o.Organization, d => d.Departament).FirstOrDefault(e => e.Id == id);

            if (employee == null)
            {
                return HttpNotFound();
            }

            if (employee.Picture != null)
            {
                byte[] image = employee.Picture.Image;
                ViewBag.Image = image;

            }

            return View(employee);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            int selectedIndex = 1;
            List<Organization> dbOrganizations = _uow.OrganizationRepository.GetItemsList().ToList<Organization>();
            SelectList organizations = new SelectList(dbOrganizations, "Id", "Name", selectedIndex);
            Organization organization = dbOrganizations.First();

            ViewBag.Organizations = organizations;
            SelectList departaments = new SelectList(organization.Departaments, "Id", "Name");
            ViewBag.Departaments = departaments;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create(Employee employee, HttpPostedFileBase uploadImage)
        {
            int selectedIndex = 1;
            Organization organization = _uow.OrganizationRepository.GetItemsList().FirstOrDefault(o => o.Id == selectedIndex);
            SelectList organizations = new SelectList(_uow.OrganizationRepository.GetItemsList(), "Id", "Name", selectedIndex);
         
            ViewBag.Organizations = organizations;
            SelectList departaments = new SelectList(organization.Departaments, "Id", "Name");
            ViewBag.Departaments = departaments;

            Picture picture = _uow.PictureRepository.GetItemsList().FirstOrDefault(e => e.Id == employee.Id);
            if (picture != null)
            {
                byte[] image = picture.Image;
                ViewBag.Image = image;

            }

            Regex regex = new Regex(@".jpg|.JPEG|.jpeg|.png|.gif");
            Notification.Notification notifi = null;
            bool validImage = true;

            if (uploadImage != null)
            {
                string extension = Path.GetExtension(uploadImage.FileName);
                validImage = regex.IsMatch(extension);
            }

            if (ModelState.IsValid && validImage)
            {
                try
                {
                    _uow.EmployeeRepository.Create(employee);
                    _uow.Save();
                }
                catch
                {
                    notifi = new Notification.Notification(NotificationType.Error, "Ошибка сохранения данных о сотруднике");
                    NotificationList.Add(notifi);
                    return View(employee);
                }

                if (uploadImage != null)
                {
                    byte[] image = null;
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {

DatabaseInitializers/Views/Employees/Create.cshtml
@model Domain.Employee

@{
    ViewBag.Title = "Создать нового сотрудники";
}

<div class="center-b">
    <h2>Создать нового сотрудники</h2>

    @using (Html.BeginForm("Create", "Employees", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>

            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Surname)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Surname, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Surname)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.BirthDate)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.BirthDate, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BirthDate)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Organization.Name);
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.OrganizationId, ViewBag.Organizations as SelectList, new { @class = "form-control" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Departament.Name);
            </div>

            <div class="editor-field">
                @Html.DropDownListFor(model => model.DepartamentId, ViewBag.Departaments as SelectList, htmlAttributes: new { @class = "form-control" })
            </div>

            <div class="editor-label">Загрузить фотографию</div>
            <div class="editor-field">
                <input type="file" class="form-control" id="download" name="uploadImage" accept="image/*" />
            </div>

            <div class="button-b">
                <input type="submit" value="Создать" class="btn btn-default"/>
                @Html.ActionLink("Вернуться к списку", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </fieldset>
    }   
</div>
@section Scripts {
    @Scripts.Render("~/bundles/createAndEdit")
}

DatabaseInitializers/Views/Employees/Delete.cshtml
@model Domain.Employee

@{
    ViewBag.Title = "Удалить работника";
}

<div class="center-b">
    <h2>Удалить работника</h2>

    <fieldset>

        @if (ViewBag.Image != null)
        {
            <div class="photo">
                @Html.Raw("<img style='width:150px; height:90px;' src=\"data:image/jpeg;base64,"
                        + Convert.ToBase64String(ViewBag.Image) + "\" />");
            </div>
        }
        <div class="display-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Surname)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Surname);
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.Organization.Name);
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Organization.Name);
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.Departament.Name);
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Departament.Name);
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.BirthDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.BirthDate)
        </div>
    </fieldset>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="button-b">
            <input type="submit" value="Удалить" class="btn btn-default"/> 
        </div>
    }
    <div>
        @Html.ActionLink("Вернуться назад к списку", "Index", null, new { @class = "btn btn-primary" })
    </div>
</div>

DatabaseInitializers/Views/Employees/DepartamentsList.cshtml
@model IEnumerable<Domain.Departament>
<select id="DepartamentId" name="DepartamentId" class="form-control">
    @foreach (var item in Model)
    {
        <option value="@item.Id">@item.Name</option>
    }
</select>

DatabaseInitializers/Views/Employees/Details.cshtml
@model Domain.Employee

@{
    ViewBag.Title = "Информация о сотруднике";
}

<div class="center-b">
    <h2>Информация о сотруднике</h2>

    <fieldset>

        @Html.HiddenFor(model => model.Id)

        @if (ViewBag.Image != null)
        {
            <div class="photo">
                @Html.Raw("<img style='width:150px; height:90px;' src=\"data:image/jpeg;base64,"
                        + Convert.ToBase64String(ViewBag.Image) + "\" />")
            </div>
        }

        <div class="display-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Surname)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Surname)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Organization)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Organization.Name)
        </div>

        <div class="display-label">
            @Html.LabelFor(model => model.Departament.Name)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Departament.Name)
        </div>
        <div class="display-label">
            @Html.LabelFor(model => model.BirthDate)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.BirthDate)
        </div>


    </fieldset>
    <div class="button-b">
        <div>
            @Html.ActionLink("Редактировать сотрудника", "Edit", new { id = Model.Id }, new { @class = "btn btn-default" })
        </div>
        <div>
            @Html.ActionLink("Вернуться назад к списку", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>

</div>

DatabaseInitializers/Views/Employees/Edit.cshtml
@model Domain.Employee

@{
    ViewBag.Title = "Редактировать сотрудника";
}

<div class="center-b">
    <h2>Редактироват сотрудника</h2>

    @using (Html.BeginForm("Edit", "Employees", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            @Html.HiddenFor(model => model.Id)
          
            @if (ViewBag.Image != null)
            {
                @Html.Hidden("pictureId", Model.Picture.Id, new { @class = "picture" })
                <div class="photo">
                    @Html.Raw("<img style='width:150px; height:90px;' src=\"data:image/jpeg;base64,"
                        + Convert.ToBase64String(ViewBag.Image) + "\" />")
                    <button class="btn btn-default picture-del">Удалить фотографию</button>
                </div>
               
            }

            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Surname)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Surname, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Surname)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Organization.Name);
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.OrganizationId, ViewBag.Organizations as SelectList, new { @class = "form-control" })
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Departament.Name)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.DepartamentId, ViewBag.Departaments as SelectList, new { @class = "form-control" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.BirthDate)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.BirthDate, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BirthDate)
            </div>

            <div class="editor-label">Загрузить фотографию</div>
            <div class="editor-field">
                <input type="file" class="form-control" id="download" name="uploadImage" accept="image/*" />
            </div>

            <div class="button-b">
                <input type="submit" value="Сохранить" class="btn btn-default"/>
                @Html.ActionLink("Вернуться назад к списку", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </fieldset>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/createAndEdit")
}

DatabaseInitializers/Views/Employees/Index.cshtml
@using EmployeeDeskBook.Models
@using EmployeeDeskBook.Helpers;
@model EmployeeFilteringViewModel



@{
    ViewBag.Title = "Список сотрудников";
}

<div class="menu">
    <div class="navigation menu-item">
 
     @if (User.IsInRole("admin"))
      {   
        <div class="item">@Html.ActionLink("Создать нового работника", "Create", "Employees", null, new { @class = "btn btn-primary" })</div>
        <div class="item">@Html.ActionLink("К списку Организаций", "Index", "Organization", null, new { @class = "btn btn-primary" })</div>
        <div class="item">@Html.ActionLink("К списку Департаментов", "Index", "Departament", null, new { @class = "btn btn-primary" })</div>
        <div class="item">@Html.ActionLink("Вход в панель администратора", "Index", "Admin", null, new { @class = "btn btn-primary" })</div>

      }
        
</div>

@section Search {
        <div class="search-block">
            <a href="/" class="btn btn-primary" id="reset">Сбросить результаты</a>
            <input type="submit" id="submit" value="Поиск" class="btn btn-default" />
            <input type="text" name="search" id="search"  data-autocomplete-source='@Url.Action("AutocompleteSearch", "Employees")' />
        </div>
    }
    <form method="get" class="filter-form menu-item">
        <div class="filter">
            <label class="control-label">Департамент</label>
            @Html.DropDownList("departamentId", ViewBag.Departaments as SelectList,
                          htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="filter birthfilter">
            <label class="control-label date-label">Дата рождения</label>
            <div class="date-filters">
                <div class="date-block">
                    <label class="control-label">От</label>
                    @Html.TextBoxFor(e => e.FromSortDate, new { @class = "birthdate form-control", Value = Model.FromSortDate } )
                    @Html.ValidationMessageFor(model => model.FromSortDate,null)
                    @*<input type="text" value="@Model.FromSortDate" name="from" class="birthdate form-control" />*@
                </div>
                <div class="date-block">
                    <label class="control-label">До</label>
                    @Html.TextBoxFor(e => e.ToSortDate, new { @class = "birthdate form-control", Value = Model.ToSortDate })
                    @Html.ValidationMessageFor(model => model.ToSortDate, null)
                    @*<input type="text" value="@Model.ToSortDate" name="to" class="birthdate form-control" />*@
                </div>
            </div>
        </div>
        <input type="submit" value="Отфильтровать" class="filter btn btn-default btn-filter" />
        @if(Model.DepartamentId != null || Model.FromSortDate != null || Model.ToSortDate != null  ) {
            <a href="/" class="btn btn-primary" id="filter-reset">Сбросить результаты</a>
        }
    </form>

</div>

<div class="data">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Организация</th>
                <th>Департамент</th>
                <th>Дата рождения</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Employees)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Organization.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Departament.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BirthDate)
                    </td>
                    <td>
                        @if (User.IsInRole("admin") || User.IsInRole("moderator"))
                        {
                            @Html.ActionLink("Редактировать информацию о работнике", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                        }
                        |
                        @Html.ActionLink("Подробнее", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                        |
                        @if (User.IsInRole("admin") || User.IsInRole("moderator"))
                        {
                            @Html.ActionLink("Удалить работника", "Delete", new { id = item.Id }, new { @class = "btn btn-primary" })
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    Страница @Model.Pager.PageNumber из @Model.Pager.TotalPages
    @Html.PageLinks(Model.Pager, page => Url.Action("Index", new { fromSortDate = Model.FromSortDate, toSortDate = Model.ToSortDate, departament = Model.DepartamentId, page }))

</div>
@section Scripts {
    @Scripts.Render("~/bundles/employee")
}